# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_VexRiscvMcuAxi_0_0/design_1_VexRiscvMcuAxi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_VexRiscvMcuAxi_0_0 || ORIG_REF_NAME==design_1_VexRiscvMcuAxi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_ram_0_0/design_1_axi_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_ram_0_0 || ORIG_REF_NAME==design_1_axi_ram_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_cdma_0_0/design_1_axi_cdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_cdma_0_0 || ORIG_REF_NAME==design_1_axi_cdma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_plic_axil_wrapper_0_0/design_1_plic_axil_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_plic_axil_wrapper_0_0 || ORIG_REF_NAME==design_1_plic_axil_wrapper_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_muxed_dual_port_ram_0_0/design_1_muxed_dual_port_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_muxed_dual_port_ram_0_0 || ORIG_REF_NAME==design_1_muxed_dual_port_ram_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_2/design_1_axi_bram_ctrl_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_2 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_1/design_1_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_1 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_1_0 || ORIG_REF_NAME==design_1_smartconnect_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axil_timer_64_0_0/design_1_axil_timer_64_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axil_timer_64_0_0 || ORIG_REF_NAME==design_1_axil_timer_64_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2c_master_axil_0_0/design_1_i2c_master_axil_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2c_master_axil_0_0 || ORIG_REF_NAME==design_1_i2c_master_axil_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_negation_0_0/design_1_negation_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_negation_0_0 || ORIG_REF_NAME==design_1_negation_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_negation_0_1/design_1_negation_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_negation_0_1 || ORIG_REF_NAME==design_1_negation_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_basic_or_0_0/design_1_basic_or_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_basic_or_0_0 || ORIG_REF_NAME==design_1_basic_or_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_negation_1_2/design_1_negation_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_negation_1_2 || ORIG_REF_NAME==design_1_negation_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_negation_1_0/design_1_negation_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_negation_1_0 || ORIG_REF_NAME==design_1_negation_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_2 || ORIG_REF_NAME==design_1_clk_wiz_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uart_bootloader_1_0/design_1_axi_uart_bootloader_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uart_bootloader_1_0 || ORIG_REF_NAME==design_1_axi_uart_bootloader_1_0} -quiet] -quiet

# XDC: /home/ryanb/Documents/MINA/hw/custom_ip/MINA_proj/MINA_proj.gen/sources_1/bd/design_1/design_1_ooc.xdc
