#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Sep 06 23:24:37 EDT 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail
# simulate design
echo "xsim tb_design_1_wrapper_behav -key {Behavioral:ram_block_tb:Functional:tb_design_1_wrapper} -tclbatch tb_design_1_wrapper.tcl -protoinst "protoinst_files/bd_48ac.protoinst" -protoinst "protoinst_files/bd_88fd.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim tb_design_1_wrapper_behav -key {Behavioral:ram_block_tb:Functional:tb_design_1_wrapper} -tclbatch tb_design_1_wrapper.tcl -protoinst "protoinst_files/bd_48ac.protoinst" -protoinst "protoinst_files/bd_88fd.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

