#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Sun Sep 06 20:32:48 EDT 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/opt/Xilinx/${SIM_VER_XSIM}/data"
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L xilinx_vip -prj VexRiscvMcuAxi_vlog.prj"
xvlog --incr --relax -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L xilinx_vip -prj VexRiscvMcuAxi_vlog.prj 2>&1 | tee compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
